---
title: "Explore temperature data"
date: 06-22-2020
output: html_notebook
---

I could do taylor diagrams for overall data and for each year? 

Start with just an average time series

Currently I have my resampled OISST data in a matlab form, monthly mean for all years. but I could grab daily ts in python?

```{r setup}

library (lubridate)
library (raster)
library (tidyverse)

# read in lat/lon sample points from MFRI
mfri_pts <- read_csv("../Data/MFRI_comb_survey_samples.csv") %>%
  dplyr::select (sample_id, date, lat, lon) %>%
  arrange (date)  #not originally in date order

# create spatialpoints dataframe
coordinates(mfri_pts) <- ~lon + lat

```

### OISST 
```{r oisst}
# brick saved in data folder
oisst_r <- brick ("../Data/OISST_MFRI.grd")
# set up a vector of dates
oisst_date <- seq (ymd("1985-01-01"), ymd("2020-06-01"), by = "months")
```

26 lat by 84 lon by 426 months. 


```{r extract_target_points}
#http://geog.uoregon.edu/bartlein/courses/geog490/week06-geospatial.html#extract-data-from-a-raster


# create an index of mfri dates to match with layers of raster brick?
match_oisst_date <- function (x) {
  date_index <-  which(oisst_date == x)
  return(date_index)
}

date_index <- sapply(mfri_pts$date, match_oisst_date)

mfri_pts$date_index <- date_index

# turn into spatialpoints
coordinates(mfri_pts) <- ~lon + lat

# try just with first date?
mfri_tmp <- mfri_pts[which (mfri_pts$date_index == 3),]

oisst_tmp <- subset (oisst_r, 3)

mfri_tmp_extract <- extract (oisst_tmp, mfri_tmp, method = "simple")

mfri_tmp_df <- data.frame (mfri_tmp$lon, mfri_tmp$lat, mfri_tmp_extract) # this seems to work!

# looks like need to do this in a loop anyway
# https://stackoverflow.com/questions/34294376/how-to-extract-data-from-a-rasterbrick

# I want to make a big dataframe, so makes more sense to build in a loop?
mfri_dates_in <- unique (mfri_pts$date_index) # 106

# make empty df
mfri_oisst_df <- data.frame(sample_id = factor(),
                            oisst = numeric())

for (x in mfri_dates_in) {
  # subset mfri data
  mfri <- mfri_pts[which (mfri_pts$date_index == x),]
  
  # subset oisst brick
  oisst_subset <- subset (oisst_r, x)
  oisst_extract <- extract (oisst_subset, mfri, method = "simple")
  
  x_df <- data.frame (sample_id = mfri$sample_id, oisst = oisst_extract)
  
  mfri_oisst_df <- rbind (mfri_oisst_df, x_df)
}

mfri_oisst_df$sample_id <- as.factor(mfri_oisst_df$sample_id)
```

```{r oisst_hist}
hist(mfri_oisst_df$oisst)
summary (mfri_oisst_df$oisst)
summary (comb_samples$surface_temp) # didn't read this in earlier
```

summaries look quite similar!

compare samples and oisst
```{r temp_bias_plots}
comb_samples_sst <- read_csv("../Data/MFRI_comb_survey_samples.csv",
                          col_types = cols(
                      sample_id = col_factor(),
                      stat_sq = col_factor())
) %>%
  left_join (mfri_oisst_df, by = "sample_id")

comb_samples_sst %>%
  ggplot (aes (x = surface_temp, y = oisst, col = season)) +
  geom_point() +
  geom_abline (slope = 1, intercept = 0)

comb_samples_sst %>%
  mutate (sst_bias = surface_temp - oisst) %>%
  ggplot (aes (x = date, y =sst_bias, col = season)) +
  geom_point() +
  geom_smooth (method = 'lm')

comb_samples_sst %>%
  mutate (sst_bias = surface_temp - oisst) %>%
  ggplot (aes (x = year, y =sst_bias, group = year)) +
  geom_boxplot() 

comb_samples_sst %>%
  mutate (sst_bias = surface_temp - oisst) %>%
  ggplot (aes (x = lat, y =sst_bias, col = season)) +
  geom_point() 
```

plot distributions?
```{r compare_density_plot}
comb_samples_sst %>%
  dplyr::select (sample_id, surface_temp, oisst) %>%
  pivot_longer (-sample_id, names_to = "source",
                values_to = "temp") %>%
  ggplot (aes (x = temp, col = source)) +
  geom_density() 
```

## GINS
```{r load_GINS}
gins_bt <- brick ("../Data/GINS_bottom_temp.grd")
dim(gins_bt)

# trickier to match dates because these are by decade. Make a vector of dates and use a series of case_when to match
gins_dates <- paste (
  rep (c(1985, 1995, 2005), each = 12),
  sprintf ("%02d", 1:12),
  "01",
  sep = "-")

```

```{r extract_gins}
# try matching one date
mfri_tmp <- mfri_pts[which (mfri_pts$date == "2000-03-01"),]

which (gins_dates == "1995-03-01") # 15

gins_tmp <- subset (gins_bt, 15)

mfri_tmp_extract <- raster::extract (gins_tmp, mfri_tmp, method = "simple")

mfri_tmp_df <- data.frame (mfri_tmp$lon, mfri_tmp$lat, mfri_tmp_extract) 


# Build a loop
mfri_dates_in <- unique (mfri_pts$date[which (mfri_pts$date < "2013-01-01")]) # 106 total dates; 73 before 2012

# make empty df
mfri_gins_df <- data.frame(sample_id = factor(),
                            gins_bt = numeric())

# doesn't like x in mfri_dates_in for some reason?
for (i in 1:length(mfri_dates_in)) {
  x <- mfri_dates_in[i]
  # subset mfri data
  mfri <- mfri_pts[which (mfri_pts$date == x),]
  
  # match date
  y <- case_when (
    between (year(x), 1985, 1994) ~ paste0 ("1985", substr(x, 5, 10)),
    between (year(x), 1995, 2004) ~ paste0 ("1995", substr(x, 5, 10)),
    between (year(x), 2005, 2012) ~ paste0 ("2005", substr(x, 5, 10))
  )
  
  #index date
  y_in <- which (gins_dates == y)
  
  # subset oisst brick
  gins_subset <- subset (gins_bt, y_in)
  gins_extract <- raster::extract (gins_subset, mfri, method = "simple")
  
  x_df <- data.frame (sample_id = mfri$sample_id, gins_bt = gins_extract)
  
  mfri_gins_df <- rbind (mfri_gins_df, x_df)
}

mfri_gins_df$sample_id <- as.factor(mfri_gins_df$sample_id)
```

```{r compare_bt}
comb_samples_bt <- read_csv("../Data/MFRI_comb_survey_samples.csv",
                          col_types = cols(
                      sample_id = col_factor(),
                      stat_sq = col_factor())
) %>%
  left_join (mfri_gins_df, by = "sample_id")

comb_samples_bt %>%
  dplyr::select (sample_id, bottom_temp, gins_bt) %>%
  pivot_longer (-sample_id, names_to = "source",
                values_to = "temp") %>%
  ggplot (aes (x = temp, col = source)) +
  geom_density() 
```

not as good match for density plot

```{r gins_temp_bias_plots}
summary (comb_samples_bt$bottom_temp)
summary (mfri_gins_df$gins_bt)

comb_samples_bt %>%
  ggplot (aes (x = bottom_temp, y = gins_bt, col = season)) +
  geom_point() +
  geom_abline (slope = 1, intercept = 0)

comb_samples_bt %>%
  mutate (bt_bias = bottom_temp - gins_bt) %>%
  ggplot (aes (x = date, y =bt_bias, col = season)) +
  geom_point() +
  geom_smooth (method = 'lm')

comb_samples_bt %>%
  mutate (bt_bias = bottom_temp - gins_bt) %>%
  ggplot (aes (x = year, y =bt_bias, group = year)) +
  geom_boxplot() 

comb_samples_bt %>%
  mutate (bt_bias = bottom_temp - gins_bt) %>%
  ggplot (aes (x = lat, y =bt_bias, col = season)) +
  geom_point() 
```